# -*- coding: utf-8 -*-
"""chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VRF3dwzJ-RdB2OCnWQzGZ_1zQHZZ9TMG
"""

import random

senoir = "elder"

reply = {
 # greetings
    "hello": ["hello there"],
    "good morning":[" good morning! how are you doing"],
    "how are you":["I'm doing great"],
  "about senoir":["my name is elder"],
  "who are you":["I'm senoir"],
  "what can i do for you":["can we be friends"],
  "yes we can":["we are friends now"],
  "you are cool":["Awnn thanks!"],
  "i love you":["that's sweet"],
  "bye":["goodbye! take care"],
  "see you":["catch you later"]
}
DEFAULT_REPLIES =["hmmm,I'm not sure about that",
                  "what are you saying?",
                    "sorry that's a bit beyond me"

  ]
def get_response(user_input):
    """find a matching responses for the user's input"""
    text = user_input.lower().strip()
    # check if user input matches or contain any of the key word
    for key, responses in reply.items(): # Changed local variable name from 'reply' to 'responses'
      if key in text:
        return random.choice(responses)
    return random.choice(DEFAULT_REPLIES)

def chat():
  print("=" * 45)
  print(f"  welcome to {senoir}")
  print("   type bye to exit")
  print("=" * 45)
  print(f"\n{senoir}:Please say something!\n")

  while True:
    user_input = input("You: ")
    response = get_response(user_input)
    print(f"{senoir} :{response}\n")

    #exit conditions
    if any (word in user_input.lower() for word in ["bye","goodbye"]):
      break

if __name__ == "__main__":
  chat()

